general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.8
    vibrancy = 0.1696
}

# Hora
label {
    monitor =
    text = $TIME
    color = rgba(216, 222, 233, 0.90)
    font_size = 80
    font_family = Noto Sans Bold
    position = 0, 150
    halign = center
    valign = center
}

# Fecha
label {
    monitor =
    text = cmd[update:60000] echo "$(LC_TIME=es_AR.UTF-8 date +"%A, %d de %B")"
    color = rgba(216, 222, 233, 0.80)
    font_size = 22
    font_family = Noto Sans
    position = 0, 60
    halign = center
    valign = center
}

# Usuario
label {
    monitor =
    text =  $USER
    color = rgba(216, 222, 233, 0.80)
    font_size = 18
    font_family = Noto Sans
    position = 0, -20
    halign = center
    valign = center
}

# Campo de contraseña
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    placeholder_text = <i>Contraseña</i>
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>Contraseña incorrecta ($ATTEMPTS)</i>
    rounding = 10
    position = 0, -100
    halign = center
    valign = center
}
